Libvisual/libvisual

- libvisual-plugins/plugins/actor/goom2k4/goomsl.c
Related: https://github.com/Libvisual/libvisual/issues/80#issuecomment-565579867
@svgmuc does this fix the issue for you?
Error was:
```
[..]/libvisual-plugins/plugins/actor/goom2k4/goomsl.c:1275:30: error: argument 1 range [18446744071562067968, 18446744073709551615] exceeds
maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
fastiflow->mallocedInstr = calloc(number*16, sizeof(FastInstruction));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> goom2k4: Address -Werror=alloc-size-larger-than= issue

- libvisual/libvisual/lv_cpu.c
> lv_cpu: Use Rip if on 64-bit Windows

- .github/workflows/windows.yml
Symptom in action: https://github.com/Libvisual/libvisual/runs/3400679130?check_suite_focus=true
Related article: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Fix GitHub Actions CI: Migrate from ::add-path to ${GITHUB_PATH} file

- .github/workflows/windows.yml
The CI started failing, e.g. see https://github.com/Libvisual/libvisual/runs/4575127948?check_suite_focus=true#step:7:21
The symptom was:
```
[..]
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc (11.2.0-5) breaks dependency 'mingw-w64-x86_64-gcc=11.2.0-4' required by mingw-w64-x86_64-libgccjit
```
> [GitHub Actions] [Windows] Uninstall mingw-w64-x86_64-libgccjit to resolve conflicts

- libvisual-plugins/configure.ac
See https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/40_lv_analyzer_build_fix.patch/
> [0.4.x] libvisual-plugins: Fixes configure so that lv_analyzer actually gets built

- libvisual-plugins/ChangeLog
- libvisual-plugins/README
- libvisual-plugins/plugins/actor/dancingparticles/actor_dancingparticles.cpp
- libvisual-plugins/plugins/actor/dancingparticles/actor_dancingparticles.h
- libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
Idea is from https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/95_fix_spelling.patch/ but this is for `master` not `0.4.x` and goes a bit further. Note that "transparant" with "a" is a thing while "transparent" with "e" is an adjective.
> libvisual-plugins: Mass-fix typo "transparant"

- libvisual-plugins/ChangeLog
- libvisual-plugins/README
- libvisual-plugins/plugins/actor/dancingparticles/actor_dancingparticles.cpp
- libvisual-plugins/plugins/actor/dancingparticles/actor_dancingparticles.h
- libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
Similar to #114 but for 0.4.x
Idea is from https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/95_fix_spelling.patch/ but this patch goes a bit further. Note that "transparant" with "a" is a thing while "transparent" with "e" is an adjective.
> [0.4.x] libvisual-plugins: Mass-fix typo "transparant"

- libvisual/libvisual/lv_plugin.c
From https://sources.debian.org/patches/libvisual/0.4.0-18/40_fix_format-security-error.patch/
> [0.4.x] libvisual: Fixes for -Werror=format-security

- libvisual/libvisual/lv_error.c
- libvisual/libvisual/lv_error.h
- libvisual/po/es_AR.po
- libvisual/po/es_ES.po
- libvisual/po/libvisual-0.4.pot
From https://sources.debian.org/patches/libvisual/0.4.0-18/50_fix-spelling-errors.patch/
> [0.4.x] libvisual: Fix typo "succesful"

- libvisual/libvisual/lv_error.c
- libvisual/libvisual/lv_error.h
- libvisual/po/es_AR.po
- libvisual/po/es_ES.po
- libvisual/po/libvisual-0.4.pot
Inspired by https://sources.debian.org/patches/libvisual/0.4.0-18/80_fix_spelling.patch/ but taken further
> [0.4.x] libvisual: Fix typo "indentical"

- libvisual/configure.ac
Inspired by https://sources.debian.org/patches/libvisual/0.4.0-18/95_fix-FTCBFS.patch/ but taken further
> [0.4.x] libvisual: Fix detection of pkg-config for cross-compilation

- libvisual-plugins/plugins/actor/nastyfft/actor_nastyfft.c
From https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/70_no-const-vispluginfo-in-nastyfft.patch/
> [0.4.x] libvisual-plugins: Fix nastyfft blocker

- libvisual-plugins/Makefile.am
- libvisual-plugins/configure.ac
```console
$ autoreconf --install --verbose |& grep -F m4 | head -n2
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
```
From https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/50_fix_po.patch/
> [0.4.x] libvisual-plugins: Make translations work properly

- libvisual-plugins/plugins/input/mplayer/input_mplayer.c
> ```
> [..]/plugins/input/mplayer/input_mplayer.c:158:33: error: cast to smaller integer type 'int' from 'mplayer_data_t *' [-Werror,-Wpointer-to-int-cast]
>         visual_log_return_val_if_fail( (int)priv->mmap_area != -1, -1 );
>                                        ^~~~~~~~~~~~~~~~~~~~
> [..]/plugins/input/mplayer/input_mplayer.c:182:7: error: cast to smaller integer type 'int' from 'mplayer_data_t *' [-Werror,-Wpointer-to-int-cast]
>         if ( (int)priv->mmap_area == -1 )
>              ^~~~~~~~~~~~~~~~~~~~
> ```
Alternative to half of https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/90_fix_some_gcc_warnings.patch/
> [0.4.x] libvisual-plugins: Address GCC/Clang warning -Wpointer-to-int-cast

- libvisual-plugins/plugins/input/mplayer/input_mplayer.c
> ```
> [..]/plugins/input/mplayer/input_mplayer.c:190:22: error: format specifies type 'int' but the argument has type 'unsigned long' [-Werror,-Wformat]
>                                 priv->mmap_area, sizeof( mplayer_data_t ),
>                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
> [..]/plugins/input/mplayer/input_mplayer.c:191:5: error: format specifies type 'int' but the argument has type 'unsigned long' [-Werror,-Wformat]
>                                 sizeof( mplayer_data_t ) + priv->mmap_area->bs,
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
Alternative to half of https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-10/90_fix_some_gcc_warnings.patch/ ; other half is #126
> [0.4.x] libvisual-plugins: Address GCC/Clang warning -Wformat

- libvisual-plugins/plugins/actor/G-Force/Common/GeneralTools/UtilStr.cpp
- libvisual-plugins/plugins/actor/G-Force/Common/UI/DrawXX.cpp
- libvisual-plugins/plugins/actor/G-Force/Common/io/CEgIStream.cpp
- libvisual-plugins/plugins/actor/G-Force/Common/math/ExprVirtualMachine.cpp
> ```
> [..]/plugins/actor/G-Force/Common/GeneralTools/UtilStr.cpp:137:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
>         register unsigned long i = 0;
>         ^~~~~~~~~
> ```
> [0.4.x] libvisual-plugins: Address Clang 16 warning -Wregister

- libvisual-plugins/plugins/actor/oinksie/gfx-scope.c
- libvisual-plugins/plugins/actor/pseudotoad_flower/notch.c
- libvisual/libvisual/lv_libvisual.c
- libvisual/libvisual/lv_math.c
- libvisual/libvisual/lv_transform.c
First raised at https://bugs.gentoo.org/871015
The precise errors fixed are:
GCC's view:
```
libvisual/lv_libvisual.c:315:9: error: implicit declaration of function 'visual_cpu_initialize'; did you mean 'visual_mem_initialize'? [-Werror=implicit-function-declaration]
libvisual/lv_transform.c:154:9: error: implicit declaration of function 'visual_transform_init'; did you mean 'visual_transform_new'? [-Werror=implicit-function-declaration]
libvisual/lv_math.c:66:13: error: implicit declaration of function 'visual_cpu_get_sse' [-Werror=implicit-function-declaration]
libvisual/lv_math.c:112:20: error: implicit declaration of function 'visual_cpu_get_3dnow' [-Werror=implicit-function-declaration]
```
Clang 16's view:
```
../../libvisual/lv_libvisual.c:315:2: error: call to undeclared function …
```
> [0.4.x] libvisual + libvisual-plugins: Address Clang 16 warning -Wimplicit-function-declaration

- libvisual/configure.ac
Effect:
```console
--- build_amd64_before/libvisual/lvconfig.h     2022-11-30 11:51:10.117382442 +0100
+++ build_amd64_after/libvisual/lvconfig.h      2022-11-30 11:52:21.197916872 +0100
@@ -28,0 +29,2 @@
+#define VISUAL_ARCH_X86_64
+
```
From https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libvisual/files/libvisual-0.4.0-detect_amd64.patch
> [0.4.x] libvisual: configure.ac: Define macro VISUAL_ARCH_X86_64 on x86_64

- .github/workflows/linux.yml
- libvisual-plugins/plugins/actor/blursk/blur.c
- libvisual-plugins/plugins/actor/blursk/blursk.c
- libvisual-plugins/plugins/actor/blursk/img.c
- libvisual-plugins/plugins/actor/gforce/Common/EgCommon.h
- libvisual-plugins/plugins/actor/gforce/GForceCommon/G-Force.cpp
- libvisual-plugins/plugins/actor/gforce/GForceCommon/Headers/G-Force.h
- libvisual-plugins/plugins/actor/goom2k4/tentacle3d.c
- libvisual-plugins/plugins/actor/jakdaw/feedback.c
- libvisual-plugins/plugins/actor/jess/draw.c
- libvisual-plugins/plugins/actor/nebulus/glthreads.c
- libvisual-plugins/plugins/actor/oinksie/gfx-background.c
- libvisual/libvisual/lv_libvisual.h
- libvisual/libvisual/lv_libvisual_c.cpp
- libvisual/libvisual/lv_plugin_registry.h
- libvisual/libvisual/lv_random.cpp
Similar to #116 but for `master` (0.5.0)
> libvisual + libvisual-plugins: Fix compilation for GCC 12 and Clang 16

- libvisual-plugins/plugins/actor/G-Force/Common/math/Expression.cpp
From https://bugs.gentoo.org/179629
> [0.4.x] libvisual-plugins: Fix G-Force compile on FreeBSD

- libvisual-plugins/configure.ac
This is patch `050_all_automagic.patch` from [`libvisual-plugins-0.4.0-patches-4.tar.bz2`](http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/distfiles/23/libvisual-plugins-0.4.0-patches-4.tar.bz2) of Gentoo Linux.
Related: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies
> [0.4.x] libvisual-plugins: configure.ac: Fix automagic

- libvisual/libvisual/lv_color.c
First raised at https://bugs.gentoo.org/859922
Note that `master` already has that problem fixed.
> [0.4.x] libvisual: Allow strict aliasing (-Werror=strict-aliasing)

- libvisual-plugins/plugins/actor/oinksie/gfx-blur.c
> ```
> [..]/plugins/actor/oinksie/gfx-blur.c:64:9: warning: unsequenced modification and access to 'buf' [-Wunsequenced]
>                         *(buf++) = valuetab[*buf];
>                              ^               ~~~
> ```
> [0.4.x] libvisual-plugins: Address Clang warning -Wunsequenced

- libvisual/libvisual/lv_color.c
Original report: https://sourceforge.net/p/libvisual/bugs/18/
```c
#include <stdint.h>
#include <stdio.h>
int main() {
int r = 0x11;
int g = 0x22;
int b = 0x33;
uint32_t colors;
colors = (256 << 24) | (r << 16) | (g << 8) | b;
printf("Old: 0x%08x\n", colors);
colors = (255 << 24) | (r << 16) | (g << 8) | b;
printf("New: 0x%08x\n", colors);
return 0;
}
```
```console
main.c: In function ‘main’:
main.c:11:23: warning: result of ‘256 << 24’ requires 34 bits to represent, but ‘int’ only has 32 bits [-Wshift-overflow=]
11 |         colors = (256 << 24) | (r << 16) | (g << 8) | b;
|                       ^~
Old: 0x00112233
New: 0xff112233
```
CC @dcb314
> [0.4.x] libvisual: Fix conversion of color to uint32

- libvisual/examples/simple/simple_example.cpp
- libvisual/libvisual/lv_cpu.c
- libvisual/tools/lv-tool/display/sdl_driver.cpp
- libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
- libvisual/tools/lv-tool/lv-tool.cpp
> libvisual: Improve lv-tool a bit

- libvisual/libvisual/lv_fourier.cpp
- libvisual/libvisual/lv_param.cpp
* Use `emplace()` instead of `insert()` or `operator[]`, where possible. Availability is guaranteed now after 10 years for the standard map containers!
* Remove spaces between closing brackets of nested templates.
> Minor C++ code improvements

- libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
Related:
- Pull request #153 
- Comment https://github.com/Libvisual/libvisual/pull/163#issuecomment-1382580104
> [0.4.x] libvisual-plugins: Free timer during cleanup for actor "lv_gltest"

- libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
Similar to pull request #153 and #164 but for `master`.
> libvisual-plugins: Base rotation on runtime not FPS for actor "lv_gltest"

- libvisual-plugins/plugins/actor/lcdcontrol/LCDGraphic.cpp
- libvisual-plugins/plugins/actor/lcdcontrol/WidgetVisualization.cpp
While stripping down the `VisVideo` API surface, I noticed that `lcdcontrol` uses `visual_video_free_buffer()` to free `VisVideo` instances. This will leak because the `VisVideo` object itself is not freed by this function. Replaced with `visual_video_unref()`.
This makes my argument that the `VisVideo` parameters should be immutable once the instance is constructed. Only its buffer contents may be changed.
> libvisual-plugins: Fix memory leak in lcdcontrol.

- libvisual-plugins/plugins/input/alsa/input_alsa.c
- libvisual-plugins/po/de.po
- libvisual-plugins/po/es_AR.po
- libvisual-plugins/po/es_ES.po
- libvisual-plugins/po/libvisual-plugins-0.4.pot
Should ideally be merged *after* pull request #152 or it will further increase the buffer overflow problem that #152 is fixing.
> [0.4.x] libvisual-plugins: Fix ALSA input plugin

- libvisual/libvisual/lv_video.h
- libvisual/libvisual/lv_video_c.cpp
Part of the ongoing API streamlining and reworking.
Two points I want to make:
- The C++ methods are retained at the moment as they are used internally by `LV::Bin`, `LV::Actor`, and `LV::Morph`. They will be removed too in time.
- I discovered more `lcdcontrol` plugin code that uses `visual_buffer_free_buffer()` to free `VisVideo` instances. They are not currently configured to build so I will leave them in for now.
> libvisual: Remove VisVideo C API for altering parameters after creation

- libvisual/tests/math_utils.hpp
LV::Tests float equality test functions are defined in the header `tests/math_util.hpp` but were missing the inline keyword. Remained undiscovered until now as it's not yet used by any testing code (but will soon be!).
I have also made the functions `constexpr` to allow compile-time evaluation by the C++ compiler. Although there isn't much of a need for this in unit tests, there is a chance we may move the functions into LV Core to provide the functionality for library users and plugins. It's also a trivial addition, so why not.
> libvisual - Bugfix and constexpr enhancements for FP tests

- libvisual/tools/lv-tool/lv-tool.cpp
Regression from 60ad4af90df1fc01a9415818aa82008fa8e84b69 of pull request #178 
Backport to 0.4.x in a minute.
> lv-tool: Fix broken --actor argument

- libvisual/README
- libvisual/README.md
Update readme files. After a decade, ORC has been brought under the GStreamer project (?), and every website has HTTPS.
@hartwork, I am wondering if we should remove README and keep only README.md.
> Core (Docs): Update links and C version requirement in readme files

- libvisual/po/de.po
- libvisual/po/es_AR.po
- libvisual/po/es_ES.po
- libvisual/po/libvisual-0.4.pot
- libvisual/tools/lv-tool/lv-tool.cpp
Inspired by https://github.com/hartwork/xmms2-devel/blob/2b8cc16791aceaf6ff121418041f1f6ae9f99c86/src/clients/vistest/libvisual.c#L142 .
> [0.4.x] lv-tool: Always skip actors "gstreamer" and "gdkpixbuf" when cycling

- libvisual/libvisual/lv_ringbuffer.c
One way to see the unfixed behavior in action is to run
1. Fire up `mplayer -af export <some_media_file>`.
2. Run `lv-tool --input mplayer`.
3. Stop mplayer playback or close mplayer.
4. Wait for lv-tool to appear frozen while running in circles in `visual_ringbuffer_get_data_offset`.
> [0.4.x] libvisual: Fix ringbuffer infinite loop

- libvisual/examples/simple/simple_example.hpp
- libvisual/tools/lv-tool/display/sdl_driver.cpp
- libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
Forward-port of 0.4.x pull request #187 to `master`
> libvisual: Fix SDL header location with regard to pkg-config, e.g. for macOS

- libvisual/tools/lv-tool/lv-tool.cpp
We can only copy 256 entries if we have them...
> [0.4.x] lv-tool: Fix check for a suitable palette

- libvisual-plugins/plugins/actor/G-Force/Common/GeneralTools/Headers/Hashable.h
- libvisual-plugins/plugins/actor/G-Force/Common/UI/PixPort.cpp
- libvisual-plugins/plugins/actor/G-Force/Makefile.am
- libvisual-plugins/plugins/actor/G-Force/unix/libmfl/mfl.c
Found running `lv-tool --switch 10` with AddressSanitizer active.
> [0.4.x] libvisual-plugins: Fix issues with object destruction and font loading for actor "gforce"

- libvisual/libvisual/lv_intrusive_ptr.hpp
Overloading of functions in `std` namespace is considered undefined behaviour by the C++ standard.
We do the Right Thing by changing `LV::IntrusivePtr`'s `swap()` to a friend function that can be found using argument-dependent lookup.
> Core (LV::IntrusivePtr): Implement swap() overload as a friend function.

- libvisual/po/de.po
- libvisual/po/es_AR.po
- libvisual/po/es_ES.po
- libvisual/po/libvisual-0.4.pot
- libvisual/tools/lv-tool/lv-tool.cpp
Follow-up to pull request #201 to prepare/precede porting to `master`
@kaixiong some choices that were intentional (but are up for discussion) are:
- I picked `set` over `vector` because it seemed to capture intent better and performance is of no concern with only 2 entries.
- I picked `set` over `unordered_set` to not require C++11.
- I picked `set.find` over `set.contains` to not require C++20.
- I chose uppercase because the data is constant in nature.
- And put it outside the function so the code is not run more times than needed.
PS: What's a good requirement for a C++ standard for 0.4.x when ideally [everyone who is on <0.4.2 today](https://repology.org/project/libvisual/badges) should be able to update? C++03, 11, 14, 17?  C++17 [seems to …
> [0.4.x] lv-tool: Resolve strcmp duplication around actors to always exclude from cycling

- libvisual/tools/lv-tool/lv-tool.cpp
Forword-port of 0.4.x pull requests #201 and #219 but with `unordered_set::contains` of C++20.
> lv-tool: Always skip actors "gstreamer" and "gdkpixbuf" when cycling

- libvisual/tools/lv-tool/lv-tool.cpp
Backport of missing pieces introduced to `master` by pull request #221, follow-up to #201 and #219
> [0.4.x] lv-tool: Move constant actors_to_skip next to its siblings

- libvisual-plugins/configure.ac
- libvisual-plugins/plugins/input/Makefile.am
- libvisual-plugins/plugins/input/pulseaudio/Makefile.am
- libvisual-plugins/plugins/input/pulseaudio/input_pulseaudio.c
This a backport from `master` to `0.4.x` (that didn't have any PulsesAudio input) followed by a migration from PulseAudio's [Simple API](https://freedesktop.org/software/pulseaudio/doxygen/simple.html) to PulseAudio's [Asynchronous API](https://freedesktop.org/software/pulseaudio/doxygen/async.html) to make it work in practice. Forward-porting this migration to `master` will be a follow-up pull request.
Related to #33.
> [0.4.x] libvisual-plugins: Add PulseAudio input plugin (based on PulseAudio's Asynchronous API)

- libvisual-plugins/plugins/input/portaudio/input_portaudio.c
Backport of finding on unused variable from `master` pull request #234 to `0.4.x`
> [0.4.x] libvisual-plugins: Improve error handling in .init of input plugin "portaudio"

- libvisual/configure.ac
- libvisual/tools/lv-tool/Makefile.am
@kaixiong this conflicts with #232 but I'm happy to rebase either side onto whatever gets merged first.
The idea is to better fit into the `libvisual-0.4` naming worlds and with the option to have two libvisual lv-tools side by side at some point. Inspired by gstreamer.
> [0.4.x] lv-tool: Rename binary from "lv-tool" to "lv-tool-0.4"

- libvisual/tools/lv-tool/lv-tool.cpp
@kaixiong it is meant to be a conservative increase and be smaller than a quarter of 1920x1080. The idea is to just show a bit more: 320x200 is just crazy tiny these days.
> [0.4.x] lv-tool: Increase initial/default resolution from 320x200 to 640x480

- libvisual-plugins/plugins/input/portaudio/input_portaudio.c
Regression from #236, `master`'s #234 turned out unaffected.
> [0.4.x] libvisual-plugins: Fix flipped assertion in .init of input "portaudio"

- libvisual/po/de.po
- libvisual/po/es_AR.po
- libvisual/po/es_ES.po
- libvisual/po/libvisual-0.4.pot
- libvisual/tools/lv-tool/lv-tool-0.4.1
- libvisual/tools/lv-tool/lv-tool.cpp
> [0.4.x] lv-tool: Demote actor "lv_analyzer" (related to #207)

- libvisual/tools/lv-tool/lv-tool.cpp
Related to #207
Forward-port of 0.4.x pull request #254
> lv-tool: Demote actor "lv_analyzer" (related to #207)

- libvisual/libvisual/lv_cpu.c
This is from https://src.fedoraproject.org/rpms/libvisual/blob/rawhide/f/libvisual-0.4.0-better-altivec-detection.patch , started out at https://bugzilla.redhat.com/show_bug.cgi?id=435771#c21 originally.
Thanks to @dwmw2!
> [0.4.x] libvisual: Improve AltiVec detection for PPC/PPC64 Linux

- libvisual/tools/lv-tool/display/sdl_driver.cpp
- libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
- libvisual/tools/lv-tool/lv-tool.cpp
Fixes #161
Forward-port of 0.4.x pull requests #210 and #249
~@kaixiong turns out that with enough mouse action over a longer period, I could still reproduce the stutter. That's why it's combined with dropping stale events now for a more complete fix, needs a backport to 0.4.x.~
> lv-tool: Debounce resize requests (fixes #161)

- libvisual/CMakeLists.txt
Rant: As usual, Microsoft does its own thing.
References:
- Documentation on Microsoft Learn ([link](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170))
- Thread on CMake ([link](https://gitlab.kitware.com/cmake/cmake/-/issues/18837))
> Core (Build): Get MSVC to use correct values for the __cplusplus define

- libvisual/tools/lv-tool/display/display.hpp
- libvisual/tools/lv-tool/display/display_driver_factory.hpp
- libvisual/tools/lv-tool/display/sdl_driver.cpp
- libvisual/tools/lv-tool/display/stdout_driver.cpp
- libvisual/tools/lv-tool/display/stdout_sdl_driver.cpp
- libvisual/tools/lv-tool/lv-tool.cpp
- Use `final` to prohibit subclassing where needed
- Use `override` instead of `virtual` when overriding virtual methods or implementing pure virtual methods.
> Core (lv-tool): Apply 'override' and 'final' to classes.

- libvisual/libvisual/lv_actor.h
- libvisual/libvisual/lv_audio.h
- libvisual/libvisual/lv_bin.h
- libvisual/libvisual/lv_buffer.h
- libvisual/libvisual/lv_color.h
- libvisual/libvisual/lv_defines.h
- libvisual/libvisual/lv_event.h
- libvisual/libvisual/lv_fourier.h
- libvisual/libvisual/lv_input.h
- libvisual/libvisual/lv_mem.h
- libvisual/libvisual/lv_morph.h
- libvisual/libvisual/lv_palette.h
- libvisual/libvisual/lv_param.h
- libvisual/libvisual/lv_param_validators.h
- libvisual/libvisual/lv_param_value.h
- libvisual/libvisual/lv_random.h
- libvisual/libvisual/lv_rectangle.h
- libvisual/libvisual/lv_songinfo.h
- libvisual/libvisual/lv_time.h
- libvisual/libvisual/lv_util.h
- libvisual/libvisual/lv_video.h
This PR adds the define `LV_NODISCARD` for marking C API functions whose return results should not be discarded. I have added them to API functions that return allocated objects.
The define uses compiler-specific function attributes to achieve this when building C code.
For C++, `[[nodiscard]]` already exists from C++17 onwards. C++20 has a variant that accepts a string literal for explaining the rationale that could be displayed in compiler messages. I can't see how to achieve the same for C unfortunately.
Use `LV_NODISCARD` only for C API functions. `[[nodiscard]]` for C++ functions.
> Core: Add LV_NODISCARD for C API functions with non-discardable results  

- libvisual/libvisual/lv_defines.h
`LV_RESTRICT` was not correctly defined when compiling with `g++` and `clang++` due to a typo in naming `__GNUC__`. This PR fixes that. This is a replacement of #266.
> Core: Fix LV_RESTRICT not correctly defined in C++ when compiling with GCC and Clang.

- libvisual-plugins/plugins/actor/corona/corona.cpp
Fixes #263
Turned to it could be triggered by resizing the window to be of tiny width.
`m_reflArray` is an array of int elements and all loops operate on `m_real_height - m_height` elements.  So if the loop code is correct, then we need `(m_real_height - m_height) * sizeof(int)` many bytes for `m_reflArray`.
Symptom through the eyes of AddressSanitizer:
> ```
> =================================================================
> ==20990==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61400000cbec at pc 0x7fe65de62216 bp 0x7ffd745ec810 sp 0x7ffd745ec808
> WRITE of size 4 at 0x61400000cbec thread T0
>     #0 0x7fe65de62215 in Corona::genReflectedWaves(double) [..]/libvisual-plugins/plugins/actor/corona/corona.cpp:311
>     #1 0x7fe65de62262 in Corona::drawReflected() …
```
> [0.4.x] libvisual-plugins: Fix allocation size in "corona" to fix heap-buffer-overflow (fixes #263)

- libvisual-plugins/plugins/actor/corona/corona.cpp
Port of 0.4.x pull request #281 to `master`
Fixes #263
Turned to it could be triggered by resizing the window to be of tiny width.
`m_reflArray` is an array of int elements and all loops operate on `m_real_height - m_height` elements.  So if the loop code is correct, then we need `(m_real_height - m_height) * sizeof(int)` many bytes for `m_reflArray`.
Symptom through the eyes of AddressSanitizer:
> ```
> =================================================================
> ==20990==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61400000cbec at pc 0x7fe65de62216 bp 0x7ffd745ec810 sp 0x7ffd745ec808
> WRITE of size 4 at 0x61400000cbec thread T0
>     #0 0x7fe65de62215 in Corona::genReflectedWaves(double) [..]/libvisual-plugins/plugins/actor/corona/corona.cpp:311
>     #1 …
```
> libvisual-plugins: Fix allocation size in "corona" to fix heap-buffer-overflow (fixes #263)

- libvisual-plugins/plugins/actor/G-Force/GForceCommon/G-Force.cpp
- libvisual-plugins/plugins/actor/G-Force/GForceCommon/Headers/G-Force.h
> [0.4.x] libvisual-plugins: Fix compile error for actor "gforce" (e.g. for macOS)

- libvisual/libvisual/lv_mem.c
> Core (Memory): Remove custom implementations of memset() and memcpy().

- libvisual/libvisual/lv_libvisual.cpp
- libvisual/libvisual/lv_libvisual.h
- libvisual/libvisual/lv_plugin_registry.cpp
- libvisual/libvisual/lv_plugin_registry.h
- libvisual/libvisual/lv_singleton.hpp
- Use `std::unique_ptr<>` to hold instance pointers.
- Mark singleton classes `final` to enable devirtualization.
> Core: Enhance and clean up singleton classes

- libvisual-plugins/plugins/actor/dancingparticles/actor_dancingparticles.cpp
- libvisual-plugins/plugins/actor/lv_gltest/actor_lv_gltest.c
- libvisual-plugins/po/de.po
- libvisual-plugins/po/es_AR.po
- libvisual-plugins/po/es_ES.po
- libvisual-plugins/po/libvisual-plugins-0.4.pot
- libvisual/README
> ```console
> git grep -l Transparant | xargs sed 's,Transparant,Transparent,g' -i
> git grep -l transparant | xargs sed 's,transparant,transparent,g' -i
> ```
Thanks to @eribertomota :+1:
> [0.4.x] libvisual + libvisual-plugins: Mass-fix typo "[Tt]ransparant" once more

- libvisual/libvisual/lv_singleton.hpp
The symbols `LV::System::m_instance` and `LV::PluginRegistry::m_instance` were not exported and this resulted in user programs and plugins having their own copies which remain uninitialized even after `LV::System::init()` or `LV::PluginRegistry::init()` was called.
Exporting the `LV::Singleton<T>` class template fixes the mysterious crashes.
The breakage first occurred in b4091ca.
@hartwork
> Core (LV::Singleton): Fix crash due to differing copies of singleton instances in LV and user programs

- .github/workflows/linux_and_macos.yml
.. because `ubuntu-22.04` suddenly dropped GCC 13.
Related:
- https://github.com/actions/runner-images/issues/9866
- https://github.com/actions/runner-images/issues/9679
> [0.4.x] `linux_and_macos.yml`: Bump to `ubuntu-24.04` and GCC 14

- .github/workflows/linux.yml
.. because `ubuntu-22.04` suddenly dropped GCC 13.
Related:
- https://github.com/actions/runner-images/issues/9866
- https://github.com/actions/runner-images/issues/9679
> `linux.yml`: Downgrade to GCC 12 to fix CI

- libvisual-plugins/configure.ac
- libvisual/configure.ac
In reaction to https://github.com/Libvisual/libvisual/issues/300#issuecomment-2323593727
> [0.4.x] libvisual + libvisual-plugins: `configure.ac`: Be more helpful in absence of autoconf-archive and/or `pkg.m4`

- .github/workflows/linux_and_macos.yml
Workaround for https://github.com/Homebrew/homebrew-core/issues/202234
> [0.4.x] Fix macOS CI / Patch `ax_check_gl.m4` of autoconf-archive 2024.10.16 as needed

- libvisual/libvisual/lv_hashmap.c
with the accidental assignment, the function would always return 0 for a keytype of VISUAL_HASHMAP_KEY_TYPE_STRING (because it has a value of 2), which is technically valid but not good for obvious reasons
> [0.4.x] libvisual: fix accidental assignment instead of equality check

- .github/workflows/linux_and_macos.yml
Homebrew started applying the patch itself by now: https://github.com/Homebrew/homebrew-core/pull/202309
This reverts commit 222b6c4d5e79807c7af06b633a902fdd83144e78 of pull request #374 .
> [0.4.x] Stop patching `ax_check_gl.m4` for macOS

- libvisual-plugins/plugins/actor/blursk/blursk.c
Blursk crashes in `__blursk_cleanup` when the plugin is loaded and unloaded multiple times. This can occur when `lv-tool` cycles through actors and completes a full rotation.
The bug is due to the sharing and re-use of the variable `config` across instances.  
`config` contains multiple strings allocated during plugin instance initialization in `config_default()`:
```C
if(conf->color_style)
visual_mem_free(conf->color_style);
conf->color_style = visual_strdup(config_default_color_style);
if(conf->signal_color)
visual_mem_free(conf->signal_color);
conf->signal_color = visual_strdup(config_default_signal_color);
```
These strings are then freed in `__blursk_cleanup()` when the plugin instance is cleaned up.
```C
visual_mem_free(config.color_style);
visual_mem_free(config.signal_color);
``` …
> Plugins (Blursk): Fix double free when Blursk is loaded multiple times.

- libvisual/libvisual/private/lv_video_png.cpp
- libvisual/tests/video_test/video_load_test.cpp
Currently, the PNG loader applies a libpng input transformation to convert 8-bit indexed colour images into 24-bit RGB images. This may be an undesirable step and inconsistent with what the BMP loader does.
This patch drops this and loads 8-bit indexed colour PNGs directly into 8-bit colour LV::Video objects. Note that 8-bit grayscale images continue to be converted to 24-bit RGB.
> Change PNG image loader to load 8-bit indexed images without format conversion 

- libvisual/libvisual/lv_video.cpp
- libvisual/libvisual/private/lv_video_bmp.cpp
This PR fixes the palette loading in the BMP image loader.
The bug is due to the loader reading from the wrong file offset.
BMP files begin with a fixed size file header and a DIB (device-independent bitmap) header that has been continually extended over the years. According to [Wikipedia](https://en.wikipedia.org/wiki/BMP_file_format), there are 8 versions of the DIB header with differing sizes. They vary from the original 12 bytes to as large as 124 bytes in recent revisions. Each version subsumes the fields of previous versions. The colour table i.e. palette is found right after [1].
The loader currently reads part of the DIB header to get what it needs and proceeds to read the palette entries without accounting for the actual DIB header size. This patch fixes this by seeking to the …
> Fix BMP palette loading

- libvisual/libvisual/lv_palette.h
This PR implements:
- standard C++ container methods such as `begin() `and `end()` for iteration
- equality and inequality operators for comparing palettes
> Add LV::Palette methods for iterations and comparisons

- libvisual-plugins/plugins/morph/alphablend/morph_alphablend.c
- libvisual/libvisual/lv_alpha_blend.c
- libvisual/libvisual/lv_alpha_blend.h
The alphablend morph uses the blending routines `visual_alpha_blend_nn()` wrongly. It passes the pixel buffer size in bytes instead of pixel count for the `size` parameter. Since buffer size is always equal or greater than pixel count (bytes per pixel >= 1 and row padding >= 0), this causes buffer overruns.
> Plugins (alphablend): Fix blending and associated crashes due to buffer overruns

- .github/workflows/linux_and_macos.yml
As of the moment, package `php` comes pre-installed and trying to apply mass-upgrades fails at `php`.
> [0.4.x] `linux_and_macos.yml`: Drop "brew update" to fix CI

- .github/workflows/linux_and_macos.yml
> The macOS 13 runner image will be retired by December 4th, 2025.
> [0.4.x] CI: Stop using about-to-be-removed image "macos-13"
