libvisual/libvisual/lv_input.h
For #80
@1480c1 does this fix compilation for you?
=> Add missing include for use of std::function (fixes #80)

libvisual-plugins/CMakeLists.txt, libvisual/CMakeLists.txt
=> CMake: Guard -Werror by -DENABLE_FATAL_WARNINGS=yes

.github/workflows/build.yaml
https://github.com/hartwork/libvisual/actions?query=branch%3Agithub-actions++
CC @1480c1
=> Make GitHub Actions compile the code and run the test suite

.github/workflows/build.yaml, libvisual-plugins/plugins/actor/goom2k4/goom_core.c, libvisual-plugins/plugins/actor/goom2k4/goomsl_yacc.y
=> CI: Enable compilation with -Werror

.github/workflows/build.yaml
Regression from 40908c4be0f7be2fdaf3947417dfdfce7f0ad583
=> CI: Fix the build by re-disabling LCDControl plugin

.github/workflows/windows.yml, libvisual/libvisual/lv_video.h
Github actions finally added msys2 to the base image, so we no longer have to pull a new image on failed cache hit.
compiling `libvisual/libvisual/lv_video_c.cpp` in mingw-w64 gcc 10.1.0 results in failure because `<string>` is not included, thus erroring out with incomplete type
```c++
FAILED: libvisual/CMakeFiles/libvisual.dir/lv_video_c.cpp.o
D:\media-autobuild_suite\msys64\mingw64\bin\ccache.exe  g++  -Dlibvisual_EXPORTS -ID:/media-autobuild_suite/build/libvisual-git/libvisual -I. -ID:/media-autobuild_suite/build/libvisual-git/libvisual/libvisual -Ilibvisual -ID:/media-autobuild_suite/msys64/mingw64/include/orc-0.4 -ID:/media-autobuild_suite/msys64/mingw64/include -O3 -fexpensive-optimizations  -std=c++11 -Wall -Wextra -Wunused  -fstrict-aliasing -mthreads -mtune=generic -O2 -pipe …
```
=> Actions: Use github's msys2, include <string> to fix compiling

.github/workflows/linux.yml, libvisual-plugins/plugins/actor/blursk/actor_blursk.c, libvisual-plugins/plugins/actor/blursk/blursk.h, libvisual-plugins/plugins/actor/gforce/GForceCommon/G-Force.cpp, libvisual-plugins/plugins/actor/nebulus/nebulus.c, libvisual-plugins/plugins/actor/nebulus/nebulus.h
Related failing CI logs:
- https://github.com/Libvisual/libvisual/actions/runs/3545118449/jobs/5971764924#step:2:57
- https://github.com/Libvisual/libvisual/actions/runs/3555285937/jobs/5971892919#step:8:79
- https://github.com/Libvisual/libvisual/actions/runs/3555329198/jobs/5971961795#step:8:251
- https://github.com/Libvisual/libvisual/actions/runs/3555348980/jobs/5971995653#step:8:533
Thanks to @erik-bershel for https://github.com/actions/runner-images/issues/6399#issuecomment-1286050292 :pray:
=> Fix Linux CI

.github/workflows/linux.yml, libvisual-plugins/plugins/actor/oinksie/Makefile.am
Related commit: 9a0b3aa328caa857a632c8ec0562c936f8b56e18
=> [0.4.x] libvisual-plugins: Fix "make dist" + cover "make dist" by GitHub Actions

libvisual-plugins/plugins/actor/G-Force/Common/GeneralTools/Headers/XPtrList.h, libvisual-plugins/plugins/actor/G-Force/Common/GeneralTools/UtilStr.cpp, libvisual-plugins/plugins/actor/G-Force/Common/GeneralTools/XPtrList.cpp, libvisual-plugins/plugins/actor/G-Force/Common/UI/DrawXX.cpp, libvisual-plugins/plugins/actor/G-Force/Common/UI/Headers/PixPort.h, libvisual-plugins/plugins/actor/G-Force/Common/UI/LineXX.cpp, libvisual-plugins/plugins/actor/G-Force/Common/UI/PixPort.cpp, libvisual-plugins/plugins/actor/G-Force/Common/math/ExprVirtualMachine.cpp, libvisual-plugins/plugins/actor/G-Force/Common/math/Expression.cpp, libvisual-plugins/plugins/actor/G-Force/GForceCommon/G-Force.cpp
Mostly a joint effort by David Leverton and Alexis Ballier from https://bugs.gentoo.org/159159
=> [0.4.x] libvisual-plugin: Fix G-Force crash on x86_64

libvisual/libvisual/lv_audio.c
Previously, twice as many bytes as available were read and written (heap-buffer-overflow) and the code was not robust towards and odd number of samples.  Thanks to [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html)!
=> [0.4.x] libvisual: Fix splitting of interleaved stereo

libvisual-plugins/plugins/input/mplayer/input_mplayer.c
Similar to pull request #158 but for `master`.
=> libvisual-plugins: Fix mplayer input plugin

libvisual-plugins/plugins/actor/bumpscope/actor_bumpscope.c, libvisual-plugins/plugins/actor/jakdaw/actor_jakdaw.c, libvisual-plugins/po/LINGUAS, libvisual-plugins/po/de.po, libvisual-plugins/po/es_AR.po, libvisual-plugins/po/es_ES.po, libvisual-plugins/po/libvisual-plugins-0.4.pot
Based on:
- https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-17/100_fix_spelling.patch/
- https://sources.debian.org/patches/libvisual-plugins/1:0.4.0%2Bdfsg1-17/110_add_de_translation.patch/
CC @eribertomota @ChrisLeick
=> [0.4.x] libvisual-plugins: Improve translations (from Debian)

libvisual-plugins/plugins/input/alsa/CMakeLists.txt, libvisual-plugins/plugins/input/alsa/input_alsa.c
Similar to pull request #151 but for `master`.
=> libvisual-plugins: Improve ALSA input plugin 

libvisual/libvisual/lv_actor.cpp, libvisual/libvisual/lv_actor.h, libvisual/libvisual/lv_input.cpp, libvisual/libvisual/lv_input.h, libvisual/libvisual/lv_morph.cpp, libvisual/libvisual/lv_morph.h, libvisual/tools/lv-tool/lv-tool.cpp
This is a foward port of 0.4.x commit e4a6cf5b60771b8cffa90834c0dd967b006bd3b1 from pull request #150 to `master`.
=> lv-tool: Upgrade default actor plugin to "lv_gltest" if available

.github/workflows/linux.yml, .github/workflows/translations.yml, libvisual-plugins/configure.ac
0.4.x backport of pull request #177
=> [0.4.x] libvisual-plugins: Update actor_pixbuf to build with GTK 3.x

libvisual/po/de.po, libvisual/po/es_AR.po, libvisual/po/es_ES.po, libvisual/po/libvisual-0.4.pot, libvisual/tools/lv-tool/lv-tool.cpp
0.4.x backport of pull request #181
=> [0.4.x] lv-tool: Fix broken --actor argument

libvisual/tools/lv-tool/lv-tool.cpp
Forward-port of improvements from `0.4.x` pull request #182 over original `master` pull request #181
=> lv-tool: Improve --actor argument

.github/workflows/linux.yml, .github/workflows/linux_and_macos.yml, libvisual/libvisual/lv_os.c
Includes two other pull requests right now…
- #187 
- #188
… but can be rebased off of these, once they are merged, for clarify.
=> [0.4.x] Actions (macOS): Start covering build on macOS

.github/workflows/linux_and_macos.yml, libvisual-plugins/configure.ac, libvisual-plugins/plugins/actor/gstreamer/actor_gstreamer.c
Fixes #95
Backport from master at commit b253f4471c0e1d3899b798be8c2b1b16eb072851 which includes recent  pull request #133
=> [0.4.x] libvisual-plugins: Upgrade to GStreamer 1.x (fixes #95)

libvisual/po/de.po, libvisual/po/es_AR.po, libvisual/po/es_ES.po, libvisual/po/libvisual-0.4.pot, libvisual/tools/lv-tool/lv-tool.cpp
0.4.x equivalent of pull request #190 with additionally needed bits backported from `master`
=> [0.4.x] lv-tool: Support toggling fullscreen through hotkey F11

libvisual-plugins/plugins/actor/flower/actor_flower.c
Forward-port of 0.4.x pull request #199
=> libvisual-plugins: Fix out-of-bounds access for actor "lv_flower"

libvisual-plugins/plugins/actor/lv_scope/actor_lv_scope.c
Forward-port of 0.4.x pull request #198
=> libvisual-plugins: Make actor "lv_scope" show silence as a solid line

.github/workflows/linux_and_macos.yml, .github/workflows/translations.yml, libvisual-plugins/plugins/actor/gstreamer/actor_gstreamer.c
> ```
> actor_gstreamer.c:276:5: error: non-void function 'act_gstreamer_render' should return a value [-Wreturn-type]
>                                 return;
>                                 ^
> actor_gstreamer.c:280:5: error: non-void function 'act_gstreamer_render' should return a value [-Wreturn-type]
>                                 return;
>                                 ^
> ```
=> [0.4.x] libvisual-plugins: Re-integrate actor "gstreamer" with GitHub Actions CI

libvisual/tools/lv-tool/CMakeLists.txt
Forward-port of 0.4.x pull request #233
=> lv-tool: Rename binary from "lv-tool" to "lv-tool-0.5"

libvisual/tools/lv-tool/lv-tool.cpp
Forward-port of 0.4.x pull request #239
=> lv-tool: Increase initial resolution from 320x200 to 640x480

libvisual/configure.ac
=> [0.4.x] libvisual: Stop using sdl-config and AM_PATH_SDL in configure.ac

libvisual-plugins/configure.ac, libvisual/configure.ac
=> [0.4.x] libvisual + libvisual-plugins: Fix compilation for Debian "bullseye"

libvisual/po/de.po, libvisual/po/es_AR.po, libvisual/po/es_ES.po, libvisual/po/libvisual-0.4.pot, libvisual/tools/lv-tool/lv-tool.cpp
Fixes #161
Started out at https://github.com/hartwork/sdl_video_demo/pull/10
=> [0.4.x] lv-tool: Debounce resize requests (fixes #161)

libvisual-plugins/plugins/input/pulseaudio/input_pulseaudio.c
=> Plugins (pulseaudio): Use C11 atomics in place of GCC/Clang extensions.

.github/workflows/linux_and_macos.yml
Related to #246
Was including…
- #214
- #276
- #277 
- #278
- #279
- #290
… previously.
=> [0.4.x] libvisual + libvisual-plugins: Cover more compilers for macOS

libvisual/libvisual/lv_mem.c, libvisual/tests/mem_test/CMakeLists.txt, libvisual/tests/mem_test/mem_set_test.cpp
=> Core (Memory): Re-implement visual_mem_set{16,32} to exploit GCC/Clang auto-vectorisation

libvisual/configure.ac
In reaction to https://github.com/Libvisual/libvisual/issues/300#issuecomment-1484167603
=> [0.4.x] libvisual: configure.ac: Resolve Bashism

.github/workflows/enforce-copies-of-help-output-in-sync.yml, .github/workflows/linux_and_macos.yml, .github/workflows/translations.yml
=> [0.4.x] Pin GitHub Actions to specific commits for security

.github/workflows/linux.yml
0.5.x edition of 0.4.x pull request #312
Related news entry:
> Jul 26th 2023 - Snapshot becomes 18, branch 17 created
=> Fix Clang 17 CI + add Clang 18 CI

libvisual-plugins/plugins/actor/lcdcontrol/GenericSerial.cpp, libvisual-plugins/plugins/actor/lcdcontrol/LCDText.cpp
Symptom was:
```
[..]/libvisual-plugins/plugins/actor/lcdcontrol/GenericSerial.cpp:141:15: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
141 |     char buff[len + 1];
|               ^~~~~~~
```
.. plus the same a few times more.
=> libvisual-plugins (lcdcontrol): Address Clang 18 warning `-Wvla-cxx-extension` to fix CI

.github/workflows/linux_and_macos.yml
=> [0.4.x] Fix CI (both Linux and macOS)

.github/workflows/linux_and_macos.yml, .github/workflows/translations.yml
In reaction to https://github.com/Libvisual/libvisual/pull/378#issuecomment-2594589849 …
=> [0.4.x] Stop installing unneeded ORC in CI
